#!/bin/sh -e


case "$1" in
  configure)
    mkdir -p /var/log/beast-alarm-server/
    if ! getent passwd beastalarm >/dev/null; then 
      useradd -c 'beastalarm' -r -U beastalarm
    fi
    chown beastalarm:beastalarm /var/log/beast-alarm-server
    chown -R beastalarm /usr/share/beast-alarm-server
    ;;
  abort-upgrade)
    :
    ;; 
  abort-remove)
    :
    ;; 
  abort-deconfigure)
    :
    ;; 
  *) echo "$0: didn't understand"
     exit 0
    ;;
esac
exit 0 
