#!/bin/sh -e


case "$1" in
  configure)
    if ! getent passwd beastalarm >/dev/null; then 
      useradd -c 'beastalarm' -r -U beastalarm
    fi 
    chown -R beastalarm /usr/share/beast-alarm-server
    service beast-alarm-server restart
    ;;
  abort-upgrade)
    :
    ;; 
  abort-remove)
    :
    ;; 
  abort-deconfigure)
    :
    ;; 
  *) echo "$0: didn't understand"
     exit 0
    ;;
esac
exit 0 
