#!/bin/sh -e


case "$1" in
  configure)
    
    if ! getent passwd jms2rdb > /dev/null 2>&1; then
      useradd -c 'jms2rdb' -r -U jms2rdb
    fi 
    chown -R jms2rdb /usr/share/beast-alarm-jms2rdb
    service beast-alarm-jms2rdb restart 
    ;;
  abort-upgrade)
    :
    ;; 
  abort-remove)
    :
    ;; 
  abort-deconfigure)
    :
    ;; 
  *) echo "$0: didn't understand"
     exit 0
    ;;
esac
exit 0 
