#!/bin/sh -e


case "$1" in
  configure)
    
    if ! getent passwd alarmnotifier > /dev/null 2>&1; then
      useradd -c 'alarmnotifier' -r -U alarmnotifier
    fi 
    chown -R alarmnotifier /usr/share/beast-alarm-notifier
    service beast-alarm-notifier restart 
    ;;
  abort-upgrade)
    :
    ;; 
  abort-remove)
    :
    ;; 
  abort-deconfigure)
    :
    ;; 
  *) echo "$0: didn't understand"
     exit 0
    ;;
esac
exit 0 
